version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  ollama_server:
    image: ollama/ollama:latest
    container_name: ollama_server
    privileged: true
    pull_policy: always
    runtime: nvidia
    tty: true
    ulimits:
      memlock: -1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    ports:
     - "11434:11434"
    #restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ${PATH_OLLAMA}:/root/.ollama
    networks:
      - red_llm




  api:
    build:
       context: .
       dockerfile: ./Dockerfile
    container_name: api
    env_file:
      - .env
    volumes:
      - ./:/app/
    ports:
      - "6677:6677"
    depends_on:
      - ollama_server
    networks:
      - red_llm

networks:
  red_llm:  # Definir una red personalizada
    driver: bridge

volumes:
  redis_data:
